services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${USERNAME}:${PASSWORD}@mongo:27017/

  flightmngr:
    pull_policy: always
    image: ghcr.io/scalabilityissues/flight-manager:main
    environment:
      DATABASE_URL: postgres://postgres:pwd@flightmngr-db:5432
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - 60051:50051

  flightmngr-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: pwd

  validationsvc:
    pull_policy: always
    image: ghcr.io/scalabilityissues/validation-service:master
    environment:
      - SIGNING_KEY=/run/secrets/validation_key
    secrets:
      - validation_key
    ports:
      - 60052:50051

secrets:
  validation_key:
    file: sign.pem
